sip:
  settings:
    bind: 172.31.11.11:5060
  profiles:
    bar:
      sip_server: 52.117.200.117:5060
      sink: apps/live_translator/configuration1
      username: '1929132'
      password: tj9uh22
      register: True
apps:
  live_translator:
    profiles:
      configuration1:
        stt_langs: ['en', 'pt']
        tts_langs: ['pt', 'en']
        outbound: sip/bar;cld=1929133
